### ISSUE TITLE
App crashes when calling recordAudio using 1.0.9

### ISSUE THREAD

**Issue by lsilva23** [cocowalla/cordova-plugin-audiorecorder#1] opened 2018-11-12 23:22 UTC
Hello!!
I am having an error when trying to record.
navigator.device.audiorecorder.recordAudio(function(data) {
						var fileURL = JSON.parse(data);
						alert(fileURL.full_path);
}, function(err) {
						
}, 300);
The APP crashes when executing this method!
Can you help me?

**Comment by cocowalla** [comment] 2018-11-13 09:36
Seems like something is messed up with the changes I made to support `cordova-android` 7+.

If you're on `cordova-android` 6.x, I'd suggest sticking with version `1.0.8` until I get around to fixing this.

Also, could you provide some more information please:

1. Is this happening on Android, iOS, or both?
2. What version of `cordova-android` and/or `cordova-ios` are you using?
3. Are you able to provide console logs from the device?

**Comment by netronicus** [comment] 2018-11-20 20:29
this is happening to me only on Android, ios it's working pretty well... here is my system info:

Ionic:

   ionic (Ionic CLI)  : 4.3.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.9

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.2, ios 4.5.5
   Cordova Plugins       : no whitelisted plugins (19 plugins total)

System:

   ios-deploy : 1.9.2
   NodeJS     : v8.10.0 (/usr/local/bin/node)
   npm        : 6.4.1
   OS         : macOS High Sierra
   Xcode      : Xcode 10.1 Build version 10B61

**Comment by cocowalla** [comment] 2018-11-20 20:33
I was looking into this this earlier today, and I think I know what the problem is.

I'll spend a bit of time on it tomorrow, and hopefully push a fix.

**Comment by netronicus** [comment] 2018-11-20 21:40
confirmed that version 1.0.8 works fine with android 6.4.0

**Comment by cocowalla** [comment] 2018-11-21 15:27
Fixed by 51f6e07, and a new version (`1.1.0`) is available on NPM

**Closed as completed by cocowalla** 2018-11-21 15:27 UTC
Labels: bug
